// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261001115007_AddMoreCategories")]
    partial class AddMoreCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Snack, bánh quy, kẹo dẻo"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Nước giải khát",
                            Description = "Nước ngọt, nước suối, trà đóng chai"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sữa & Đồ uống dinh dưỡng",
                            Description = "Sữa tươi, sữa hộp, sữa dinh dưỡng"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mì & Thực phẩm ăn liền",
                            Description = "Mì gói, cháo ăn liền, phở ăn liền"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị nấu ăn",
                            Description = "Nước mắm, nước tương, muối, đường"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Dầu ăn",
                            Description = "Dầu đậu nành, dầu hướng dương, dầu thực vật"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Gạo & Thực phẩm khô",
                            Description = "Gạo, đậu, bột và các loại thực phẩm khô"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Đồ hộp",
                            Description = "Cá hộp, thịt hộp, pate và thực phẩm đóng hộp"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Cà phê & Trà",
                            Description = "Cà phê hòa tan, cà phê rang xay và trà"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Bánh mì & Bánh ngọt",
                            Description = "Bánh mì, bánh bông lan và bánh ngọt"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Kem & Thực phẩm đông lạnh",
                            Description = "Kem, xúc xích và các loại thực phẩm đông lạnh"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Đồ dùng nhà bếp",
                            Description = "Màng bọc thực phẩm, túi đựng và đồ dùng nhà bếp"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Giấy & Khăn giấy",
                            Description = "Khăn giấy, giấy vệ sinh và giấy lau"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Chăm sóc cá nhân",
                            Description = "Dầu gội, sữa tắm và sản phẩm vệ sinh cá nhân"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Kem đánh răng & Bàn chải",
                            Description = "Kem đánh răng, bàn chải và sản phẩm chăm sóc răng miệng"
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "Nước giặt & Nước xả",
                            Description = "Nước giặt, bột giặt và nước xả vải"
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "Nước rửa chén & Vệ sinh",
                            Description = "Nước rửa chén và các sản phẩm vệ sinh nhà cửa"
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "Đồ dùng học tập",
                            Description = "Bút, vở, thước và các dụng cụ học tập"
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "Đồ dùng cá nhân",
                            Description = "Khẩu trang, bàn chải, lược và đồ dùng cá nhân"
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "Đồ gia dụng",
                            Description = "Các vật dụng gia đình và đồ dùng sinh hoạt hằng ngày"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
