// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    partial class SupermarketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Snack, bánh quy, kẹo dẻo"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Nước giải khát",
                            Description = "Nước ngọt, nước suối, trà đóng chai"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sữa & Đồ uống dinh dưỡng",
                            Description = "Sữa tươi, sữa hộp, sữa dinh dưỡng"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mì & Thực phẩm ăn liền",
                            Description = "Mì gói, cháo ăn liền, phở ăn liền"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị nấu ăn",
                            Description = "Nước mắm, nước tương, muối, đường"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Dầu ăn",
                            Description = "Dầu đậu nành, dầu hướng dương, dầu thực vật"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Gạo & Thực phẩm khô",
                            Description = "Gạo, đậu, bột và các loại thực phẩm khô"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Đồ hộp",
                            Description = "Cá hộp, thịt hộp, pate và thực phẩm đóng hộp"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Cà phê & Trà",
                            Description = "Cà phê hòa tan, cà phê rang xay và trà"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Bánh mì & Bánh ngọt",
                            Description = "Bánh mì, bánh bông lan và bánh ngọt"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Kem & Thực phẩm đông lạnh",
                            Description = "Kem, xúc xích và các loại thực phẩm đông lạnh"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Đồ dùng nhà bếp",
                            Description = "Màng bọc thực phẩm, túi đựng và đồ dùng nhà bếp"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Giấy & Khăn giấy",
                            Description = "Khăn giấy, giấy vệ sinh và giấy lau"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Chăm sóc cá nhân",
                            Description = "Dầu gội, sữa tắm và sản phẩm vệ sinh cá nhân"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Kem đánh răng & Bàn chải",
                            Description = "Kem đánh răng, bàn chải và sản phẩm chăm sóc răng miệng"
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "Nước giặt & Nước xả",
                            Description = "Nước giặt, bột giặt và nước xả vải"
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "Nước rửa chén & Vệ sinh",
                            Description = "Nước rửa chén và các sản phẩm vệ sinh nhà cửa"
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "Đồ dùng học tập",
                            Description = "Bút, vở, thước và các dụng cụ học tập"
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "Đồ dùng cá nhân",
                            Description = "Khẩu trang, bàn chải, lược và đồ dùng cá nhân"
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "Đồ gia dụng",
                            Description = "Các vật dụng gia đình và đồ dùng sinh hoạt hằng ngày"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "125 Nguyễn Trãi, Phường Bến Thành, TP. Hồ Chí Minh",
                            CustomerName = "Nguyễn Văn Anh",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "45 Lê Lợi, Phường Sài Gòn, TP. Hồ Chí Minh",
                            CustomerName = "Trần Thị Bích Ngọc",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 50
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "78 Nguyễn Văn Linh, Phường Tân Hưng, TP. Hồ Chí Minh",
                            CustomerName = "Lê Văn Cường",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 10
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "230 Điện Biên Phủ, Phường Gia Định, TP. Hồ Chí Minh",
                            CustomerName = "Phạm Thị Diễm My",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0934455667",
                            RewardPoints = 200
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "56 Phan Văn Trị, Phường Gò Vấp, TP. Hồ Chí Minh",
                            CustomerName = "Hoàng Văn Đức",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0977788990",
                            RewardPoints = 80
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "102 Quang Trung, Phường Thông Tây Hội, TP. Hồ Chí Minh",
                            CustomerName = "Võ Thị Thanh Hương",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0961234567",
                            RewardPoints = 25
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "88 Nguyễn Xí, Phường Bình Lợi Trung, TP. Hồ Chí Minh",
                            CustomerName = "Đặng Văn Giang",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0923456789",
                            RewardPoints = 175
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "15 Cách Mạng Tháng Tám, Phường Bàn Cờ, TP. Hồ Chí Minh",
                            CustomerName = "Bùi Thị Kim Ngân",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0902233445",
                            RewardPoints = 65
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "67 Trường Chinh, Phường Tân Bình, TP. Hồ Chí Minh",
                            CustomerName = "Đỗ Minh Khang",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0913344556",
                            RewardPoints = 30
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "190 Hoàng Văn Thụ, Phường Phú Nhuận, TP. Hồ Chí Minh",
                            CustomerName = "Nguyễn Thị Thu Hà",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0984455667",
                            RewardPoints = 220
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "25 Lạc Long Quân, Phường Hòa Bình, TP. Hồ Chí Minh",
                            CustomerName = "Trần Quốc Bảo",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0935566778",
                            RewardPoints = 90
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "140 Âu Cơ, Phường Tân Hòa, TP. Hồ Chí Minh",
                            CustomerName = "Lê Thị Minh Châu",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0976677889",
                            RewardPoints = 15
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "39 Võ Văn Ngân, Phường Thủ Đức, TP. Hồ Chí Minh",
                            CustomerName = "Phan Thanh Tùng",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0967788991",
                            RewardPoints = 300
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "81 Kha Vạn Cân, Phường Linh Xuân, TP. Hồ Chí Minh",
                            CustomerName = "Huỳnh Thị Lan Anh",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0928899001",
                            RewardPoints = 110
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "210 Nguyễn Duy Trinh, Phường Long Trường, TP. Hồ Chí Minh",
                            CustomerName = "Ngô Văn Phúc",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0909900112",
                            RewardPoints = 35
                        },
                        new
                        {
                            CustomerId = 16,
                            Address = "72 Tô Ngọc Vân, Phường Tam Bình, TP. Hồ Chí Minh",
                            CustomerName = "Mai Thị Ngọc Hân",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0911011223",
                            RewardPoints = 250
                        },
                        new
                        {
                            CustomerId = 17,
                            Address = "48 Phạm Văn Đồng, Phường Hiệp Bình, TP. Hồ Chí Minh",
                            CustomerName = "Trương Minh Quân",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0982122334",
                            RewardPoints = 75
                        },
                        new
                        {
                            CustomerId = 18,
                            Address = "115 Lê Văn Việt, Phường Tăng Nhơn Phú, TP. Hồ Chí Minh",
                            CustomerName = "Đinh Thị Mỹ Linh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0933233445",
                            RewardPoints = 40
                        },
                        new
                        {
                            CustomerId = 19,
                            Address = "93 Nguyễn Thị Thập, Phường Tân Mỹ, TP. Hồ Chí Minh",
                            CustomerName = "Cao Văn Thành",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0974344556",
                            RewardPoints = 180
                        },
                        new
                        {
                            CustomerId = 20,
                            Address = "160 Huỳnh Tấn Phát, Phường Tân Thuận, TP. Hồ Chí Minh",
                            CustomerName = "Dương Thị Thùy Trang",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0965455667",
                            RewardPoints = 95
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8931111111111",
                            CategoryId = 1,
                            Price = 12000m,
                            ProductName = "Snack Khoai Tây Lay's Vị Tự Nhiên",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8932222222222",
                            CategoryId = 2,
                            Price = 10000m,
                            ProductName = "Nước Ngọt Coca-Cola Lon 320ml",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8933333333333",
                            CategoryId = 3,
                            Price = 8500m,
                            ProductName = "Sữa Tươi TH True Milk 180ml",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8934444444444",
                            CategoryId = 4,
                            Price = 4500m,
                            ProductName = "Mì Hảo Hảo Tôm Chua Cay",
                            StockQuantity = 500
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8935555555555",
                            CategoryId = 5,
                            Price = 25000m,
                            ProductName = "Nước Mắm Nam Ngư Đệ Nhị 900ml",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8936666666666",
                            CategoryId = 6,
                            Price = 55000m,
                            ProductName = "Dầu Ăn Simply Đậu Nành 1 Lít",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8930000000007",
                            CategoryId = 7,
                            Price = 180000m,
                            ProductName = "Gạo ST25 Túi 5kg",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8930000000008",
                            CategoryId = 8,
                            Price = 22000m,
                            ProductName = "Cá Hộp Ba Cô Gái 155g",
                            StockQuantity = 65
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8930000000009",
                            CategoryId = 9,
                            Price = 48000m,
                            ProductName = "Cà Phê G7 Hòa Tan Hộp 20 Gói",
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8930000000010",
                            CategoryId = 10,
                            Price = 42000m,
                            ProductName = "Bánh Bông Lan Solite Hộp 360g",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "8930000000011",
                            CategoryId = 11,
                            Price = 45000m,
                            ProductName = "Kem Merino Vani Hộp 450ml",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "8930000000012",
                            CategoryId = 12,
                            Price = 28000m,
                            ProductName = "Màng Bọc Thực Phẩm Ringo 30cm",
                            StockQuantity = 55
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "8937777777777",
                            CategoryId = 13,
                            Price = 45000m,
                            ProductName = "Lốc 6 Cuộn Giấy Vệ Sinh Bless You",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "8938888888888",
                            CategoryId = 14,
                            Price = 165000m,
                            ProductName = "Dầu Gội Clear Men Bạc Hà 630g",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "8939999999999",
                            CategoryId = 15,
                            Price = 38000m,
                            ProductName = "Kem Đánh Răng P/S Trà Xanh 230g",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 16,
                            Barcode = "8930000000000",
                            CategoryId = 16,
                            Price = 210000m,
                            ProductName = "Nước Giặt Omo Matic Cửa Trước 3.6kg",
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductId = 17,
                            Barcode = "8930000000017",
                            CategoryId = 17,
                            Price = 32000m,
                            ProductName = "Nước Rửa Chén Sunlight Chanh 750ml",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 18,
                            Barcode = "8930000000018",
                            CategoryId = 18,
                            Price = 18000m,
                            ProductName = "Vở Học Sinh Campus 200 Trang",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 19,
                            Barcode = "8930000000019",
                            CategoryId = 19,
                            Price = 35000m,
                            ProductName = "Khẩu Trang Y Tế Hộp 50 Cái",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 20,
                            Barcode = "8930000000020",
                            CategoryId = 20,
                            Price = 25000m,
                            ProductName = "Hộp Nhựa Đựng Thực Phẩm Duy Tân 1 Lít",
                            StockQuantity = 70
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
